### ISSUE TITLE
Initialize anynet.Net with Params?

### ISSUE THREAD

**Issue by wenkesj** [unixpickle/anynet#1]
Can I initialize a network with parameters? Or should I go through each layer and init the parameters from there? I am having trouble recognizing if there is this capability. Essentially, I am trying to accomplish something like this:

```go
parameters := net.Parameters()
params := make([]anyvec.Vector, len(parameters))
for i, param := range parameters {
	params[i] = param.Output()
}

// And possible the reverse?
for i, param := range parameters {
	param[i].Set(someVector)
}
```

**Comment by unixpickle** [comment]
Most layers automatically initialize themselves with random values, or have a method to do that. If you want some kind of custom initialization, you can simply set the parameters in a loop. A parameter is an `*anydiff.Var`, so you can update it's contents with a vector via `param.Vector.Set(myVector)`.

See [here](https://github.com/unixpickle/neurocli/blob/6a187bc77ebc0f27445f166023e7bf0a930d50d5/params.go#L57-L69) for a concrete example of where I do something like this. In that example, I read vectors from standard input and update network parameters based on those vectors.

**Comment by wenkesj** [comment]
Cool! Thanks, it paid off
