### ISSUE TITLE
[Feature] MIMO Networks

### ISSUE THREAD

**Issue by wenkesj** [unixpickle/anynet#2]
Do you plan on supporting `MIMO DAGs` similar to [nngraph](https://github.com/torch/nngraph)? Or is this possible in the framework already?

**Comment by wenkesj** [comment]
`anygraph` or `anydag` would be interesting with split, merge, bottle, etc.?

**Comment by unixpickle** [comment]
If I'm understanding this right, the tool would basically take in an `anynet.Layer` and produce a visualization of it? That shouldn't be very difficult, provided the network only uses building blocks from `anynet` and friends. I will see if I have time for this at some point, but it's not a priority atm.

**Comment by wenkesj** [comment]
@unixpickle more like the interface for `any.Net` being a `Directed Acyclic Graph` instead of a `slice`:
```go
type Net []Layer
```
Something like:
```go
type Net GraphOfLayers
```
It would be interesting to see a graph of channels representing the layers of the network

**Comment by unixpickle** [comment]
the `anynet.Net` type is really just a tool for composing `anynet.Layer`s. Using `anydiff`, you can compute any arbitrary differentiable function you want without building a graph. I don't see any need to explicitly represent a graph, besides perhaps making cool pictures ;)

EDIT: I suppose another benefit of declaring a graph is that you could serialize it easily. Certainly something to consider.
